# Site settings
title: AI Portfolio Bhawna
description: A brief description of the AI Nexus Exhibit site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brupani.github.io/ai-nexus-exhibit" # the base hostname & protocol for your site

# Build settings
# Build settings
source: src
# destination: _site
# markdown: kramdown
# theme: minima
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Other settings
paginate: 5
paginate_path: "/page:num/"
